const TelegramBot = require("node-telegram-bot-api");
const fetch = require("node-fetch");

// 🔐 Token daga Render ENV
const TOKEN = process.env.TELEGRAM_BOT_TOKEN;

// 🌐 API na Tele-tech-AI
const API_URL = "https://tele-tech-ai.onrender.com/generate";

// 🛑 Idan babu token, kada a fara bot
if (!TOKEN) {
  console.error("❌ TELEGRAM_BOT_TOKEN not set");
  process.exit(1);
}

// ✅ FARA BOT (POLLING KADAI – SAU 1)
const bot = new TelegramBot(TOKEN, {
  polling: {
    interval: 1000,
    autoStart: true
  }
});

// /start
bot.onText(/^\/start$/, (msg) => {
  bot.sendMessage(
    msg.chat.id,
    "👋 Welcome to *Tele Image AI*\n\n🎨 Aiko da rubutu (prompt) domin a ƙirƙiri hoto.\n\nMisali:\n`A realistic lion wearing a crown`",
    { parse_mode: "Markdown" }
  );
});

// Karɓar prompt
bot.on("message", async (msg) => {
  const chatId = msg.chat.id;
  const prompt = msg.text;

  if (!prompt || prompt.startsWith("/")) return;

  await bot.sendMessage(chatId, "🎨 Generating image, please wait...");

  try {
    const res = await fetch(API_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        email: `telegram_${chatId}@user.com`,
        prompt
      })
    });

    const data = await res.json();

    if (data.error) {
      await bot.sendMessage(chatId, "❌ " + data.error);
      return;
    }

    await bot.sendPhoto(chatId, data.image, {
      caption: "✅ Generated by Tele Image AI"
    });

  } catch (err) {
    console.error(err);
    await bot.sendMessage(chatId, "⚠️ Server error, try again later");
  }
});

console.log("🤖 Telegram bot is running...");
